-- MySQL Script generated by MySQL Workbench
-- Fri Dec  2 09:19:54 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Club-Bentin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Club-Bentin` ;

-- -----------------------------------------------------
-- Schema Club-Bentin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Club-Bentin` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `Club-Bentin` ;

-- -----------------------------------------------------
-- Table `Club-Bentin`.`Padres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Padres` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Padres` (
  `ID_Padres` INT NOT NULL,
  `Nombres_Padres` VARCHAR(30) NULL,
  `ApellidoM_Padres` VARCHAR(20) NULL,
  `ApellidoP_Padres` VARCHAR(20) NULL,
  `Telefono_Padres` VARCHAR(9) NULL,
  PRIMARY KEY (`ID_Padres`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Alumnos` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Alumnos` (
  `ID_Alumnos` INT NOT NULL,
  `Nacimiento_Alumno` DATE NOT NULL,
  `Teléfono_Alumno` VARCHAR(9) NOT NULL,
  `Nombres_Alumno` VARCHAR(50) NOT NULL,
  `ApllidoM_Alumno` VARCHAR(30) NOT NULL,
  `ApellidoP_Alumno` VARCHAR(30) NOT NULL,
  `Padres_ID_Padres` INT NOT NULL,
  PRIMARY KEY (`ID_Alumnos`),
  CONSTRAINT `fk_Alumnos_Padres1`
    FOREIGN KEY (`Padres_ID_Padres`)
    REFERENCES `Club-Bentin`.`Padres` (`ID_Padres`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Categorías_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Categorías_productos` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Categorías_productos` (
  `ID_Categorias` INT NOT NULL,
  `Tipo_Categorías` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_Categorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Productos` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Productos` (
  `ID_Productos` INT NOT NULL,
  `Nombre_Productos` VARCHAR(25) NULL,
  `Precio_Productos` INT NULL,
  `Stock_Productos` INT NULL,
  `Categorías_productos_ID_Categorias` INT NOT NULL,
  PRIMARY KEY (`ID_Productos`),
  CONSTRAINT `fk_Productos_Categorías_productos`
    FOREIGN KEY (`Categorías_productos_ID_Categorias`)
    REFERENCES `Club-Bentin`.`Categorías_productos` (`ID_Categorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Recibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Recibo` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Recibo` (
  `ID_Recibo` INT NOT NULL,
  `Pago_Recibo` FLOAT NULL,
  `Fecha_Recibo` DATE NULL,
  `Hora_Recibo` TIME NULL,
  PRIMARY KEY (`ID_Recibo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Tipo_usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Tipo_usuarios` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Tipo_usuarios` (
  `ID_Tipo_Usuarios` INT NOT NULL,
  `Nombre_Tipo_Usuarios` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_Tipo_Usuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Usuarios` (
  `ID_Usuarios` INT NOT NULL,
  `Nombre_Usuarios` VARCHAR(50) NOT NULL,
  `ApellidoM_Usuarios` VARCHAR(30) NOT NULL,
  `ApellidoP_Usuarios` VARCHAR(30) NOT NULL,
  `Nick_Usuarios` VARCHAR(20) NOT NULL,
  `Contraseña_Usuarios` VARCHAR(15) NOT NULL,
  `DNI_Usuarios` VARCHAR(8) NULL,
  `Email_Usuarios` VARCHAR(60) NULL,
  `Telefono_Usuarios` VARCHAR(9) NULL,
  `Tipo_usuarios_ID_Tipo_Usuarios` INT NOT NULL,
  PRIMARY KEY (`ID_Usuarios`),
  CONSTRAINT `fk_Usuarios_Tipo_usuarios1`
    FOREIGN KEY (`Tipo_usuarios_ID_Tipo_Usuarios`)
    REFERENCES `Club-Bentin`.`Tipo_usuarios` (`ID_Tipo_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Categoria` (
  `ID_Categoria` INT NOT NULL,
  `Tipo_Categoria` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_Categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Cursos` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Cursos` (
  `ID_cursos` INT NOT NULL,
  `Nombre_Curso` VARCHAR(20) NOT NULL,
  `Costo_Curso` FLOAT NOT NULL,
  `Fecha_Curso` DATE NOT NULL,
  `CantMeses_Curso` INT NOT NULL,
  `Categoria_ID_Categoria` INT NOT NULL,
  PRIMARY KEY (`ID_cursos`),
  CONSTRAINT `fk_Cursos_Categoria1`
    FOREIGN KEY (`Categoria_ID_Categoria`)
    REFERENCES `Club-Bentin`.`Categoria` (`ID_Categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Matricula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Matricula` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Matricula` (
  `ID_Matricula` INT NOT NULL,
  `Cursos_ID_cursos` INT NOT NULL,
  `Alumnos_ID_Alumnos` INT NOT NULL,
  `Fecha_Matrícula` DATE NOT NULL,
  `CostoIns_Matrícula` FLOAT NOT NULL,
  `Descuento_Marícula` FLOAT NOT NULL,
  PRIMARY KEY (`ID_Matricula`),
  CONSTRAINT `fk_Matricula_Cursos1`
    FOREIGN KEY (`Cursos_ID_cursos`)
    REFERENCES `Club-Bentin`.`Cursos` (`ID_cursos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Matricula_Alumnos1`
    FOREIGN KEY (`Alumnos_ID_Alumnos`)
    REFERENCES `Club-Bentin`.`Alumnos` (`ID_Alumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Estado_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Estado_pago` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Estado_pago` (
  `ID_Pago_mes` INT NOT NULL,
  `Enero` INT NULL,
  `Febrero` INT NULL,
  `Marzo` INT NULL,
  `Abril` INT NULL,
  `Mayo` INT NULL,
  `Junio` INT NULL,
  `Julio` INT NULL,
  `Agosto` INT NULL,
  `Septiembre` INT NULL,
  `Octubre` INT NULL,
  `Noviembre` INT NULL,
  `Diciembre` INT NULL,
  PRIMARY KEY (`ID_Pago_mes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Tipo-Pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Tipo-Pago` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Tipo-Pago` (
  `ID_Tipo_Pago` INT NOT NULL,
  `Modalidad_Tipo_Pago` VARCHAR(20) NULL,
  PRIMARY KEY (`ID_Tipo_Pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Pagos` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Pagos` (
  `ID_Pagos` INT NOT NULL,
  `Fecha_Pagos` INT NOT NULL,
  `Matricula_ID_Matricula` INT NOT NULL,
  `Recibo_ID_Recibo` INT NOT NULL,
  `Estado_pago_ID_Pago_mes` INT NOT NULL,
  `Tipo-Pago_ID_Tipo_Pago` INT NOT NULL,
  PRIMARY KEY (`ID_Pagos`),
  CONSTRAINT `fk_Pagos_Matricula1`
    FOREIGN KEY (`Matricula_ID_Matricula`)
    REFERENCES `Club-Bentin`.`Matricula` (`ID_Matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagos_Recibo1`
    FOREIGN KEY (`Recibo_ID_Recibo`)
    REFERENCES `Club-Bentin`.`Recibo` (`ID_Recibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagos_Estado_pago1`
    FOREIGN KEY (`Estado_pago_ID_Pago_mes`)
    REFERENCES `Club-Bentin`.`Estado_pago` (`ID_Pago_mes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagos_Tipo-Pago1`
    FOREIGN KEY (`Tipo-Pago_ID_Tipo_Pago`)
    REFERENCES `Club-Bentin`.`Tipo-Pago` (`ID_Tipo_Pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Tipo_cambio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Tipo_cambio` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Tipo_cambio` (
  `ID_Tipo_cambio` INT NOT NULL,
  `Estado_Tipo_cambio` VARCHAR(8) NULL,
  PRIMARY KEY (`ID_Tipo_cambio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Club-Bentin`.`Historico_productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Club-Bentin`.`Historico_productos` ;

CREATE TABLE IF NOT EXISTS `Club-Bentin`.`Historico_productos` (
  `ID_Ventas` INT NOT NULL,
  `CantCambio_Historico_productos` INT NULL,
  `TipoCambio_Historico_productos` INT NULL,
  `Tipo_cambio_ID_Tipo_cambio` INT NOT NULL,
  `Productos_ID_Productos` INT NOT NULL,
  `Usuarios_ID_Usuarios` INT NOT NULL,
  PRIMARY KEY (`ID_Ventas`),
  CONSTRAINT `fk_Historico_productos_Tipo_cambio1`
    FOREIGN KEY (`Tipo_cambio_ID_Tipo_cambio`)
    REFERENCES `Club-Bentin`.`Tipo_cambio` (`ID_Tipo_cambio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historico_productos_Productos1`
    FOREIGN KEY (`Productos_ID_Productos`)
    REFERENCES `Club-Bentin`.`Productos` (`ID_Productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historico_productos_Usuarios1`
    FOREIGN KEY (`Usuarios_ID_Usuarios`)
    REFERENCES `Club-Bentin`.`Usuarios` (`ID_Usuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
